### ISSUE TITLE
cisco_asa show interface detail issue

### ISSUE THREAD

**Issue by gbs098** [networktocode/ntc-templates#1538] opened 2023-10-06 07:50 UTC
##### ISSUE TYPE

TextFSMError: State Error raised. Rule Line: 118. Input Line:   Hardware is Virtual   MAC address 0000.0000.0000, MTU 1500

##### TEMPLATE USING

```
cisco_asa_show_interface_detail.textfsm
```

##### SAMPLE COMMAND OUTPUT

```
Interface Virtual0 "_internal_loopback", is up, line protocol is up
  Hardware is Virtual   MAC address 0000.0000.0000, MTU 1500
        IP address 127.1.0.1, subnet mask 255.255.0.0
  Traffic Statistics for "_internal_loopback":
        1 packets input, 28 bytes
        1 packets output, 28 bytes
        1 packets dropped
      1 minute input rate 0 pkts/sec,  0 bytes/sec
      1 minute output rate 0 pkts/sec,  0 bytes/sec
      1 minute drop rate, 0 pkts/sec
      5 minute input rate 0 pkts/sec,  0 bytes/sec
      5 minute output rate 0 pkts/sec,  0 bytes/sec
      5 minute drop rate, 0 pkts/sec
  Control Point Interface States:
        Interface number is 16
        Interface config status is active
        Interface state is active
```

##### STEPS TO REPRODUCE

```yaml

```

##### ACTUAL RESULTS

```

```

**Comment by mjbear** [comment] 2023-12-29 01:56
Hello @gbs098 
This issue seems to be caused by the fact that hardware type, MAC address, and MTU are all on the same line.
`Hardware is Virtual   MAC address 0000.0000.0000, MTU 1500`

I'll take a poke at this one.

**Comment by mjbear** [comment] 2023-12-29 02:37
@gbs098 
Please confirm your example output is definitely the `show interface detail` from an ASA and not just `show interface`?

Thank you.

**Comment by mjbear** [comment] 2023-12-29 03:07
@gbs098 
I submitted PR #1583 which modifies the template to make things work.

Worth noting that I did not add a capture group for `packets dropped` since it did not match up with other _more specific_ "packet drop" capture groups. The input/output packets and bytes are captured though.

**Comment by ryanmerolle** [comment] 2024-06-19 03:22
This was merged, please close issue.

**Closed** 2024-06-19 14:40 UTC
